### PR TITLE
Add embed::stub::spi

### LINKED ISSUE #26: embed::stub::spi
Implementation of the spi interface that does nothing.

### PR DESCRIPTION
**Pull request by herculanodavi**
Resolves #26

### CODE REVIEW

**Comment by herculanodavi** [comment]
Sorry, I'm not having success in getting a nice commit history.

**Review by kammce — APPROVED** [review]

**Comment by kammce** [comment]
Thanks for the PR @herculanodavi!

**Comment by kammce** [comment]
@herculanodavi If you decide you want to pick up some other issues can you consider looking into some that are not stubs. I like to use those as intro issue for people to get started. I think a good next step would be to work on some mocks. Also consider joining our discord as well if you would like to discuss this stuff as well as attend our bi-weekly meetings. 😄

**Comment by herculanodavi** [comment]
@kammce That sounds good, I just cannot find any discord links in the documentation. About the mocks, I'll try my first one in the next days then. Thanks!

**Comment by kammce** [comment]
@herculanodavi try this link https://discord.gg/p5A6vzv8tm

**Comment by kammce** [comment]
I just submitted a change so that the discord badge is on the README now.

**Pull request merged**
